import { FormSchema } from "./jsonSchema";

export const sampleForm: FormSchema = {
    formId: "form001",
    formTitle: "IEEE Form",
    description: "Please fill out this form.",
    formFields: [
      {
        fieldId: "fullName",
        fieldType: "Short Input Fields",
        label: "Full Name",
        description: "Enter your full name",
        placeholder: "John Doe",
        required: true,
        minWords: 1,
        maxWords: 3,
      },
      {
        fieldId: "bio",
        fieldType: "Text area",
        label: "Short Bio",
        description: "Tell us something about yourself (min 10 and max 200 words)",
        placeholder: "Write a short introduction...",
        required: true,
        minWords: 10,
        maxWords: 200,
      },
      {
        fieldId: "gender",
        fieldType: "Radio",
        label: "Gender",
        description: "Select your gender",
        required: true,
        options: ["Male", "Female", "Other"],
      },  
      {
        fieldId: "email",
        fieldType: "Email",
        label: "Email Address",
        description: "Enter your email",
        placeholder: "example@example.com",
        required: true,
      },
      {
        fieldId: "ieeeMember",
        fieldType: "Dropdown",
        label: "Are you an IEEE member?",
        description: "Select Yes if you are an IEEE member",
        required: true,
        options: ["Yes", "No"],
      },
      {
        fieldId: "ieeeId",
        fieldType: "IEEE Member ID",
        label: "IEEE Member ID",
        description: "Enter your IEEE membership ID",
        placeholder: "123456",
        required: true,
        conditionalLogic: {
          fieldId: "ieeeMember",
          value: "Yes",
          operator: "equals",
        },
      },
      {
        fieldId: "skills",
        fieldType: "Multiple choice",
        label: "Select your skills",
        description: "You can choose multiple skills",
        required: true,
        options: ["JavaScript", "Python", "C++", "Java"],
      },
      {
        fieldId: "file",
        fieldType: "File upload",
        label: "Upload File",
        description: "Allowed formats: PDF, DOCX ",
        required: true,
        fileTypes: ["pdf", "docx"],
        maxFileSize: 5, 
      },
      {
        fieldId: "dob",
        fieldType: "Date Picker",
        label: "Date",
        description: "Select  date ",
        placeholder: "YYYY-MM-DD",
        required: true,
      },
      {
        fieldId: "preferredTime",
        fieldType: "Time picker",
        label: "Preferred Contact Time",
        description: "When should we contact you?",
        placeholder: "HH:MM",
        required: true,
      },
    ],
  };